#!/bin/sh
# Interop tests: our SSH engine (build/sshc) against a throwaway OpenSSH sshd
# running unprivileged on localhost.  Run from the project root: make interop
ROOT=$(cd "$(dirname "$0")/.." && pwd)
SSHC=${SSHC:-$ROOT/build/sshc}
T=$(mktemp -d "${TMPDIR:-/tmp}/sshc-test.XXXXXX")
PORT=${PORT:-22222}
ME=$(id -un)
pass=0; fail=0

cleanup() { [ -f "$T/sshd.pid" ] && kill "$(cat "$T/sshd.pid")" 2>/dev/null; rm -rf "$T"; }
trap cleanup EXIT

ok()   { pass=$((pass+1)); printf '  ok   %s\n' "$1"; }
bad()  { fail=$((fail+1)); printf '  FAIL %s\n' "$1"; [ -n "$2" ] && printf '       %s\n' "$2"; }

ssh-keygen -q -t ed25519 -N "" -f "$T/host"
ssh-keygen -q -t ed25519 -N "" -f "$T/user"
ssh-keygen -q -t ed25519 -N "" -f "$T/stranger"
ssh-keygen -q -t ed25519 -N "s3cret phrase" -a 8 -f "$T/locked"
ssh-keygen -q -t ed25519 -N "cbc phrase" -a 8 -Z aes256-cbc -f "$T/locked_cbc"
ssh-keygen -q -t rsa -b 2048 -N "" -f "$T/u_rsa2048"
ssh-keygen -q -t rsa -b 4096 -N "rsa phrase" -a 6 -f "$T/u_rsa4096_enc"
ssh-keygen -q -t ecdsa -b 256 -N "" -f "$T/u_ec256"
ssh-keygen -q -t ecdsa -b 384 -N "" -f "$T/u_ec384"
ssh-keygen -q -t ecdsa -b 521 -N "ec phrase" -a 6 -f "$T/u_ec521_enc"
ssh-keygen -q -t rsa -b 2048 -N "" -m PEM -f "$T/u_rsa_pem"
ssh-keygen -q -t ecdsa -b 256 -N "" -m PEM -f "$T/u_ec_pem"
cat "$T/user.pub" "$T/locked.pub" "$T/locked_cbc.pub" "$T"/u_*.pub > "$T/authorized_keys"
cat > "$T/sshd_config" <<CFG
Port $PORT
ListenAddress 127.0.0.1
HostKey $T/host
PidFile $T/sshd.pid
AuthorizedKeysFile $T/authorized_keys
UsePAM no
PasswordAuthentication no
KbdInteractiveAuthentication no
StrictModes no
RekeyLimit 256K
LogLevel DEBUG1
Subsystem sftp /usr/libexec/sftp-server
CFG
/usr/sbin/sshd -f "$T/sshd_config" -E "$T/sshd.log" || { echo "could not start sshd"; exit 1; }
sleep 1
HOSTFP=$(ssh-keygen -lf "$T/host.pub" | awk '{print $2}')
SFTPC=${SFTPC:-$(dirname "$SSHC")/sftpc}
sf() { "$SFTPC" -p $PORT -i "$T/user" "$ME@127.0.0.1" "$@"; }
run() { "$SSHC" -p $PORT -i "$T/user" "$@" "$ME@127.0.0.1"; }

echo "== basics"
out=$(run -e 'echo hello') ; [ "$out" = "hello" ] && ok "exec echo" || bad "exec echo" "got: $out"
run -e 'exit 7' ; rc=$?; [ $rc -eq 7 ] && ok "exit status 7" || bad "exit status" "rc=$rc"
out=$(run -e 'echo to-stderr 1>&2' 2>&1 >/dev/null); [ "$out" = "to-stderr" ] && ok "stderr channel" || bad "stderr" "got: $out"
out=$(run -F "$HOSTFP" -e 'echo pinned'); [ "$out" = "pinned" ] && ok "correct pinned fingerprint accepted" || bad "pinned fp" "$out"
run -F "SHA256:wrongwrongwrongwrongwrongwrongwrongwrongwro" -e 'echo x' >/dev/null 2>&1; [ $? -ne 0 ] && ok "wrong fingerprint rejected" || bad "wrong fingerprint accepted"
"$SSHC" -p $PORT -i "$T/stranger" "$ME@127.0.0.1" -e 'echo x' >/dev/null 2>&1; [ $? -ne 0 ] && ok "unauthorised key rejected" || bad "unauthorised key accepted"

echo "== passphrase-protected keys"
out=$(SSHC_PASSPHRASE="s3cret phrase" "$SSHC" -p $PORT -i "$T/locked" -e 'echo locked-ok' "$ME@127.0.0.1" 2>&1)
[ "$out" = "locked-ok" ] && ok "login with an encrypted key (aes256-ctr, bcrypt)" || bad "encrypted key login" "$out"
out=$(SSHC_PASSPHRASE="cbc phrase" "$SSHC" -p $PORT -i "$T/locked_cbc" -e 'echo cbc-ok' "$ME@127.0.0.1" 2>&1)
[ "$out" = "cbc-ok" ] && ok "login with an encrypted key (aes256-cbc, bcrypt)" || bad "cbc key login" "$out"
out=$(SSHC_PASSPHRASE="not the phrase" "$SSHC" -p $PORT -i "$T/locked" -e 'echo x' "$ME@127.0.0.1" 2>&1); rc=$?
[ $rc -ne 0 ] && echo "$out" | grep -q "incorrect passphrase" && ok "wrong passphrase is refused with a clear message" || bad "wrong passphrase" "rc=$rc $out"
out=$("$SSHC" -p $PORT -i "$T/locked" -e 'echo x' "$ME@127.0.0.1" 2>&1); rc=$?
[ $rc -ne 0 ] && echo "$out" | grep -q "passphrase-protected" && ok "missing passphrase is reported, not a crash" || bad "no passphrase" "rc=$rc $out"

echo "== keys generated by this code (as the app's Generate Key does)"
MK=${MKKEY:-$(dirname "$SSHC")/mkkey}
for variant in plain protected; do
  if [ $variant = plain ]; then PW=""; else PW="gen pass phrase"; fi
  fp=$("$MK" "$T/gen_$variant" "$PW" "gen-$variant") || bad "mkkey $variant" "failed"
  # 1. the real ssh-keygen must read our file and derive the same public key we wrote
  theirs=$(ssh-keygen -y -P "$PW" -f "$T/gen_$variant" 2>&1 | cut -d' ' -f1,2)
  ours=$(cut -d' ' -f1,2 "$T/gen_$variant.pub")
  [ "$theirs" = "$ours" ] && ok "ssh-keygen reads our $variant private key and derives the same public key" || bad "ssh-keygen vs ours ($variant)" "$theirs"
  # 2. and computes the same fingerprint
  theirfp=$(ssh-keygen -lf "$T/gen_$variant.pub" | awk '{print $2}')
  [ "$theirfp" = "$fp" ] && ok "fingerprint matches ssh-keygen ($variant)" || bad "fingerprint ($variant)" "$theirfp vs $fp"
  # 3. a real sshd accepts a login with it, via our client
  cat "$T/gen_$variant.pub" >> "$T/authorized_keys"
  out=$(SSHC_PASSPHRASE="$PW" "$SSHC" -p $PORT -i "$T/gen_$variant" -e 'echo gen-ok' "$ME@127.0.0.1" 2>&1)
  [ "$out" = "gen-ok" ] && ok "sshd accepts a login with our generated $variant key" || bad "login with generated key ($variant)" "$out"
done
mode=$(stat -f %Lp "$T/gen_protected" 2>/dev/null || stat -c %a "$T/gen_protected")
[ "$mode" = "600" ] && ok "private key file is written mode 0600" || bad "private key permissions" "$mode"

echo "== RSA and ECDSA user keys (all sshd-accepted signature algorithms)"
for spec in "u_rsa2048:" "u_rsa4096_enc:rsa phrase" "u_ec256:" "u_ec384:" "u_ec521_enc:ec phrase" "u_rsa_pem:" "u_ec_pem:"; do
  k=${spec%%:*}; pw=${spec#*:}
  out=$(SSHC_PASSPHRASE="$pw" "$SSHC" -p $PORT -i "$T/$k" -v -e 'echo key-ok' "$ME@127.0.0.1" 2>&1)
  echo "$out" | grep -q "^key-ok" && ok "login with $k" || bad "login with $k" "$(echo "$out" | tail -2)"
done

echo "== RSA / ECDSA host keys (server offers only that type)"
hostkey_test() {   # label, key-type-args, HostKeyAlgorithms value, expected key type in the prompt
  label=$1; alg=$3; want=$4
  rm -f "$T/hk" "$T/hk.pub"
  ssh-keygen -q -N "" -f "$T/hk" $2
  cat > "$T/sshd_hk_config" <<CFG
Port $((PORT + 1))
ListenAddress 127.0.0.1
HostKey $T/hk
PidFile $T/sshd_hk.pid
AuthorizedKeysFile $T/authorized_keys
UsePAM no
PasswordAuthentication no
StrictModes no
HostKeyAlgorithms $alg
CFG
  /usr/sbin/sshd -f "$T/sshd_hk_config" -E "$T/sshd_hk.log"; sleep 1
  fp=$(ssh-keygen -lf "$T/hk.pub" | awk '{print $2}')
  out=$("$SSHC" -p $((PORT + 1)) -i "$T/user" -F "$fp" -v -e 'echo hk-ok' "$ME@127.0.0.1" 2>&1)
  echo "$out" | grep -q "^hk-ok" && echo "$out" | grep -q "host key $want $fp" && ok "$label host key verified ($want)" || bad "$label host key" "$(echo "$out" | tail -3)"
  kill "$(cat "$T/sshd_hk.pid")" 2>/dev/null; sleep 0.5
}
hostkey_test "RSA 2048 (rsa-sha2-512)" "-t rsa -b 2048" "rsa-sha2-512,rsa-sha2-256" ssh-rsa
hostkey_test "RSA 4096 (rsa-sha2-256)" "-t rsa -b 4096" "rsa-sha2-256" ssh-rsa
hostkey_test "ECDSA P-256" "-t ecdsa -b 256" "ecdsa-sha2-nistp256" ecdsa-sha2-nistp256
hostkey_test "ECDSA P-384" "-t ecdsa -b 384" "ecdsa-sha2-nistp384" ecdsa-sha2-nistp384
hostkey_test "ECDSA P-521" "-t ecdsa -b 521" "ecdsa-sha2-nistp521" ecdsa-sha2-nistp521
hostkey_test "RSA with SHA-1 (legacy ssh-rsa)" "-t rsa -b 2048" "ssh-rsa" ssh-rsa

echo "== key exchange methods (client forced onto each; the server allows everything it can)"
KEXCFG=$T/sshd_kex_config
cat > "$KEXCFG" <<CFG
Port $((PORT + 2))
ListenAddress 127.0.0.1
HostKey $T/host
PidFile $T/sshd_kex.pid
AuthorizedKeysFile $T/authorized_keys
UsePAM no
PasswordAuthentication no
StrictModes no
RekeyLimit 256K
LogLevel DEBUG1
KexAlgorithms $(ssh -Q kex | paste -sd, -)
Ciphers $(ssh -Q cipher | paste -sd, -)
MACs $(ssh -Q mac | paste -sd, -)
CFG
if /usr/sbin/sshd -f "$KEXCFG" -E "$T/sshd_kex.log"; then
  sleep 1
  KSSHC() { "$SSHC" -p $((PORT + 2)) -i "$T/user" "$@" "$ME@127.0.0.1"; }
  supported=$(ssh -Q kex)
  for k in curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 \
           diffie-hellman-group-exchange-sha256 diffie-hellman-group16-sha512 diffie-hellman-group14-sha256 diffie-hellman-group14-sha1; do
    if ! echo "$supported" | grep -qx "$k"; then echo "  skip $k (this ssh does not implement it)"; continue; fi
    out=$(KSSHC -k "$k" -v -e 'echo kex-ok' 2>&1)
    echo "$out" | grep -q "^kex-ok" && echo "$out" | grep -q "kex=$k " && ok "key exchange $k" || bad "key exchange $k" "$(echo "$out" | tail -2)"
  done
  echo "== legacy ciphers and MACs (only chosen when the server offers nothing better)"
  for c in aes128-cbc aes256-cbc; do
    for m in hmac-sha1 hmac-sha1-etm@openssh.com hmac-sha2-256 hmac-sha2-256-etm@openssh.com; do
      out=$(KSSHC -c $c -m $m -v -e 'echo legacy-ok' 2>&1)
      echo "$out" | grep -q "^legacy-ok" && echo "$out" | grep -q "cipher=$c mac=$m " && ok "$c / $m" || bad "$c / $m" "$(echo "$out" | tail -2)"
    done
  done
  for c in aes256-ctr aes128-ctr; do
    out=$(KSSHC -c $c -m hmac-sha1 -v -e 'echo legacy-ok' 2>&1)
    echo "$out" | grep -q "^legacy-ok" && echo "$out" | grep -q "cipher=$c mac=hmac-sha1 " && ok "$c / hmac-sha1" || bad "$c / hmac-sha1" "$(echo "$out" | tail -2)"
  done
  echo "== bulk data through re-keying with the new methods (RekeyLimit 256K)"
  want=$(seq 1 300000 | cksum)
  for combo in "diffie-hellman-group14-sha256|aes128-cbc|hmac-sha1" "diffie-hellman-group-exchange-sha256|aes256-cbc|hmac-sha1-etm@openssh.com" \
               "ecdh-sha2-nistp384|aes256-ctr|hmac-sha2-512" "diffie-hellman-group14-sha1|aes128-ctr|hmac-sha1"; do
    k=${combo%%|*}; rest=${combo#*|}; c=${rest%%|*}; m=${rest#*|}
    before=$(grep -c "SSH2_MSG_NEWKEYS sent" "$T/sshd_kex.log")
    got=$(KSSHC -k "$k" -c "$c" -m "$m" -e 'seq 1 300000' | cksum)
    after=$(grep -c "SSH2_MSG_NEWKEYS sent" "$T/sshd_kex.log")
    n=$((after - before - 1))
    [ "$got" = "$want" ] && [ $n -ge 3 ] && ok "$k + $c + $m: data intact across $n re-keys" || bad "bulk $k $c $m" "re-keys=$n cksum=$got"
  done
  kill "$(cat "$T/sshd_kex.pid")" 2>/dev/null
else
  bad "could not start the kex sshd" "$(tail -3 "$T/sshd_kex.log")"
fi

echo "== cipher x MAC matrix"
for c in chacha20-poly1305@openssh.com aes256-ctr aes128-ctr; do
  for m in hmac-sha2-256-etm@openssh.com hmac-sha2-512-etm@openssh.com hmac-sha2-256 hmac-sha2-512; do
    [ "$c" = chacha20-poly1305@openssh.com ] && [ "$m" != hmac-sha2-256-etm@openssh.com ] && continue
    out=$(run -v -c "$c" -m "$m" -e 'echo matrix-ok' 2>&1)
    if echo "$out" | grep -q "matrix-ok" && echo "$out" | grep -q "cipher=$c"; then ok "$c / $m"; else bad "$c / $m" "$(echo "$out" | tail -2)"; fi
  done
done

echo "== bulk data with server-initiated re-keying (RekeyLimit 256K)"
want=$(seq 1 400000 | cksum)
for c in chacha20-poly1305@openssh.com aes256-ctr; do
  got=$(run -c $c -e 'seq 1 400000' | cksum)
  [ "$got" = "$want" ] && ok "download 2.6MB intact ($c)" || bad "download ($c)" "want $want got $got"
done
dd if=/dev/urandom of="$T/blob" bs=1024 count=3000 2>/dev/null
want=$(cksum < "$T/blob")
for c in chacha20-poly1305@openssh.com aes128-ctr; do
  got=$(run -c $c -e 'cksum' < "$T/blob")
  [ "$got" = "$want" ] && ok "upload 3MB intact ($c)" || bad "upload ($c)" "want $want got $got"
done
# One 2.6MB transfer with RekeyLimit 256K must complete many key exchanges on that one connection.
before=$(grep -c "SSH2_MSG_NEWKEYS sent" "$T/sshd.log")
got=$(run -c aes256-ctr -e 'seq 1 400000' | cksum)
after=$(grep -c "SSH2_MSG_NEWKEYS sent" "$T/sshd.log")
n=$((after - before - 1))          # minus the initial exchange
[ "$got" = "$(seq 1 400000 | cksum)" ] && [ $n -ge 5 ] && ok "survived $n re-keys mid-transfer, data intact" || bad "re-keying" "re-keys=$n cksum=$got"

echo "== interactive shell with pty"
out=$(printf 'echo PTY_$((6*7))\nexit\n' | run 2>&1)
echo "$out" | grep -q "PTY_42" && ok "pty + shell" || bad "pty + shell" "$(echo "$out" | tail -3)"

echo "== SFTP (real sftp-server)"
R=$T/remote; mkdir "$R" "$R/sub"
printf 'hello\n' > "$R/a.txt"; : > "$R/empty"; printf 'x' > "$R/sp ace é.txt"
dd if=/dev/urandom of="$R/b3.bin" bs=1024 count=3000 2>/dev/null
out=$(sf ls "$R" | cut -d' ' -f1,3- | tr '\n' ';')          # "type name;" sorted bytewise: "sp" < "su"
[ "$out" = "- a.txt;- b3.bin;- empty;- sp ace é.txt;d sub;" ] && ok "directory listing (names, types, spaces, non-ASCII)" || bad "ls" "$out"
[ "$(sf ls "$R" | grep ' b3.bin' | cut -d' ' -f2)" = "3072000" ] && ok "listing reports file sizes" || bad "ls sizes"
[ "$(sf realpath . )" = "$(cd "$HOME" && pwd -P)" ] && ok "realpath of . is the home directory" || bad "realpath" "$(sf realpath .)"

want=$(cksum < "$R/b3.bin")
sf get "$R/b3.bin" "$T/dl.bin" >/dev/null && [ "$(cksum < "$T/dl.bin")" = "$want" ] && ok "download 3 MB intact (pipelined)" || bad "download 3MB"
sf put "$T/dl.bin" "$R/up.bin" >/dev/null && [ "$(cksum < "$R/up.bin")" = "$want" ] && ok "upload 3 MB intact (pipelined)" || bad "upload 3MB"
dd if=/dev/urandom of="$T/big.bin" bs=1048576 count=20 2>/dev/null; wantbig=$(cksum < "$T/big.bin")
sf put "$T/big.bin" "$R/big.bin" >/dev/null && [ "$(cksum < "$R/big.bin")" = "$wantbig" ] && ok "upload 20 MB intact" || bad "upload 20MB"
rm -f "$T/big2.bin"; sf get "$R/big.bin" "$T/big2.bin" >/dev/null && [ "$(cksum < "$T/big2.bin")" = "$wantbig" ] && ok "download 20 MB intact" || bad "download 20MB"
sf put "$R/empty" "$R/empty2" >/dev/null && [ -f "$R/empty2" ] && [ ! -s "$R/empty2" ] && ok "zero-byte file uploads" || bad "empty upload"
sf get "$R/empty" "$T/empty.dl" >/dev/null && [ -f "$T/empty.dl" ] && [ ! -s "$T/empty.dl" ] && ok "zero-byte file downloads" || bad "empty download"
sf get "$R/sp ace é.txt" "$T/sp.dl" >/dev/null && [ "$(cat "$T/sp.dl")" = "x" ] && ok "file names with spaces and non-ASCII characters" || bad "odd name"
chmod 640 "$T/dl.bin"; sf put "$T/dl.bin" "$R/perm.bin" >/dev/null; [ "$(stat -f %Lp "$R/perm.bin" 2>/dev/null || stat -c %a "$R/perm.bin")" = "640" ] && ok "upload keeps the local file mode" || bad "upload mode"

sf mkdir "$R/newdir" >/dev/null && [ -d "$R/newdir" ] && ok "mkdir" || bad "mkdir"
[ "$(sf stat "$R/newdir")" = "size=$(stat -f %z "$R/newdir" 2>/dev/null || stat -c %s "$R/newdir") mode=755 dir" ] || [ "$(sf stat "$R/newdir" | sed 's/size=[0-9]* //')" = "mode=755 dir" ] && ok "stat reports type and mode" || bad "stat" "$(sf stat "$R/newdir")"
sf chmod 700 "$R/newdir" >/dev/null && [ "$(sf stat "$R/newdir" | sed 's/size=[0-9]* //')" = "mode=700 dir" ] && ok "chmod" || bad "chmod"
sf mv "$R/a.txt" "$R/newdir/moved.txt" >/dev/null && [ -f "$R/newdir/moved.txt" ] && [ ! -e "$R/a.txt" ] && ok "rename / move" || bad "mv"
sf rm "$R/newdir/moved.txt" >/dev/null && [ ! -e "$R/newdir/moved.txt" ] && ok "remove file" || bad "rm"
sf rmdir "$R/newdir" >/dev/null && [ ! -d "$R/newdir" ] && ok "remove directory" || bad "rmdir"
out=$(sf mkdir "$R/s1" + put "$R/empty" "$R/s1/e" + ls "$R/s1" 2>&1); [ "$out" = "transferred 0 bytes
- 0 e" ] && ok "several commands share one session" || bad "multi-command session" "$out"

mkdir "$R/many"; i=0; while [ $i -lt 3000 ]; do : > "$R/many/f$i"; i=$((i+1)); done
[ "$(sf ls "$R/many" | wc -l | tr -d ' ')" = "3000" ] && ok "a 3000-entry directory lists completely (paged READDIR)" || bad "big directory" "$(sf ls "$R/many" | wc -l)"

out=$(sf get "$R/nonexistent" "$T/x" 2>&1); rc=$?
[ $rc -ne 0 ] && echo "$out" | grep -qi "no such file" && ok "downloading a missing file reports 'No such file'" || bad "missing file" "rc=$rc $out"
out=$(sf put "$T/dl.bin" "/nonexistent-dir/x" 2>&1); rc=$?
[ $rc -ne 0 ] && echo "$out" | grep -qiE "no such file|failure" && ok "uploading into a missing directory fails cleanly" || bad "missing dir" "rc=$rc $out"
out=$(sf put "$T/dl.bin" "/etc/sftp-test-denied" 2>&1); rc=$?
[ $rc -ne 0 ] && echo "$out" | grep -qi "permission denied" && ok "permission denied is reported" || bad "permission denied" "rc=$rc $out"
out=$(sf rmdir "$R/nonexistent" 2>&1); rc=$?; [ $rc -ne 0 ] && ok "rmdir of a missing directory fails" || bad "rmdir missing"

out=$(SFTPC_CANCEL_AFTER=200000 sf get "$R/big.bin" "$T/part.bin" + ls "$R/sub" 2>&1)
echo "$out" | head -1 | grep -qE "^cancelled after [0-9]+ bytes" && [ "$(stat -f %z "$T/part.bin" 2>/dev/null || stat -c %s "$T/part.bin")" -lt 20971520 ] && ok "a transfer can be cancelled mid-flight" || bad "cancel" "$out"
echo "$out" | sed -n 2p | grep -q "" ; [ "$(echo "$out" | wc -l | tr -d ' ')" = "1" ] && ok "after a cancel the same connection still works (next command ran)" || bad "session after cancel" "$out"

echo
echo "interop: $pass passed, $fail failed"
[ $fail -eq 0 ]
