/*
 * AES-128/192/256, table-driven in 32-bit words: one 1 KB table each way (TE0 for encryption, TD0 for
 * decryption, generated by tools/gen_tables.py), with the other three columns of the usual four-table
 * formulation obtained by rotating a lookup by 8, 16 or 24 bits.  The state is four big-endian words,
 * s[j] = bytes 4j..4j+3 of the block, and the round-key words in c->rk are in the same order.
 * (This replaced a byte-at-a-time SubBytes/ShiftRows/MixColumns; see the git history.)
 *
 * Table lookups indexed by secret bytes are as cache-timing-visible as the S-box lookups they
 * replaced -- adequate for a client on a 1990s workstation; prefer chacha20-poly1305 where offered.
 */
#include <string.h>
#include "aes.h"
#include "aes_tab.h"

#define XTIME(x) ((u8)(((x) << 1) ^ ((((x) >> 7) & 1) * 0x1b)))

/* t ^= x rotated right by 8 / 16 / 24 bits.  x is evaluated once (it is a table load). */
#define XOR_R8(t, x)  do { u32 a_ = (x); (t) ^= (a_ >> 8)  | (a_ << 24); } while (0)
#define XOR_R16(t, x) do { u32 a_ = (x); (t) ^= (a_ >> 16) | (a_ << 16); } while (0)
#define XOR_R24(t, x) do { u32 a_ = (x); (t) ^= (a_ >> 24) | (a_ << 8);  } while (0)

/* InvMixColumns of one round-key word, for the decryption key schedule. */
static u32 inv_mix_word(u32 w)
{
    u32 r = TD0[SBOX[w >> 24]];
    XOR_R8(r,  TD0[SBOX[(w >> 16) & 0xff]]);
    XOR_R16(r, TD0[SBOX[(w >> 8) & 0xff]]);
    XOR_R24(r, TD0[SBOX[w & 0xff]]);
    return r;
}

void aes_ctr_init(aes_ctr_ctx *c, const u8 *key, int keylen, const u8 iv[16])
{
    int nk = keylen / 4, nr = nk + 6, total = 4 * (nr + 1), i, r, j;
    u32 rcon = 1, t;
    u32 *w = c->rk;

    c->rounds = nr;
    for (i = 0; i < nk; i++) w[i] = LOAD32_BE(key + 4 * i);
    for (i = nk; i < total; i++) {
        t = w[i - 1];
        if (i % nk == 0) {
            t = ((u32)SBOX[(t >> 16) & 0xff] << 24) | ((u32)SBOX[(t >> 8) & 0xff] << 16) |
                ((u32)SBOX[t & 0xff] << 8) | (u32)SBOX[(t >> 24) & 0xff];
            t ^= rcon << 24;
            rcon = XTIME(rcon) & 0xff;
        } else if (nk > 6 && i % nk == 4) {
            t = ((u32)SBOX[(t >> 24) & 0xff] << 24) | ((u32)SBOX[(t >> 16) & 0xff] << 16) |
                ((u32)SBOX[(t >> 8) & 0xff] << 8) | (u32)SBOX[t & 0xff];
        }
        w[i] = w[i - nk] ^ t;
    }

    /* Equivalent inverse cipher (FIPS-197 5.3.5): the round keys in reverse order, with InvMixColumns
     * applied to all but the first and last. */
    for (r = 0; r <= nr; r++)
        for (j = 0; j < 4; j++) {
            u32 k = w[4 * (nr - r) + j];
            c->drk[4 * r + j] = (r == 0 || r == nr) ? k : inv_mix_word(k);
        }

    memcpy(c->ctr, iv, 16);
    c->used = 16;
}

void aes_encrypt_block(const aes_ctr_ctx *c, const u8 in[16], u8 out[16])
{
    const u32 *rk = c->rk;
    u32 s0, s1, s2, s3, t0, t1, t2, t3;
    int r;

    s0 = LOAD32_BE(in)      ^ rk[0];
    s1 = LOAD32_BE(in + 4)  ^ rk[1];
    s2 = LOAD32_BE(in + 8)  ^ rk[2];
    s3 = LOAD32_BE(in + 12) ^ rk[3];
    for (r = 1; r < c->rounds; r++) {
        rk += 4;
        t0 = TE0[s0 >> 24] ^ rk[0]; XOR_R8(t0, TE0[(s1 >> 16) & 0xff]); XOR_R16(t0, TE0[(s2 >> 8) & 0xff]); XOR_R24(t0, TE0[s3 & 0xff]);
        t1 = TE0[s1 >> 24] ^ rk[1]; XOR_R8(t1, TE0[(s2 >> 16) & 0xff]); XOR_R16(t1, TE0[(s3 >> 8) & 0xff]); XOR_R24(t1, TE0[s0 & 0xff]);
        t2 = TE0[s2 >> 24] ^ rk[2]; XOR_R8(t2, TE0[(s3 >> 16) & 0xff]); XOR_R16(t2, TE0[(s0 >> 8) & 0xff]); XOR_R24(t2, TE0[s1 & 0xff]);
        t3 = TE0[s3 >> 24] ^ rk[3]; XOR_R8(t3, TE0[(s0 >> 16) & 0xff]); XOR_R16(t3, TE0[(s1 >> 8) & 0xff]); XOR_R24(t3, TE0[s2 & 0xff]);
        s0 = t0; s1 = t1; s2 = t2; s3 = t3;
    }
    rk += 4;                                        /* last round: SubBytes + ShiftRows only */
    t0 = ((u32)SBOX[s0 >> 24] << 24) ^ ((u32)SBOX[(s1 >> 16) & 0xff] << 16) ^ ((u32)SBOX[(s2 >> 8) & 0xff] << 8) ^ (u32)SBOX[s3 & 0xff] ^ rk[0];
    t1 = ((u32)SBOX[s1 >> 24] << 24) ^ ((u32)SBOX[(s2 >> 16) & 0xff] << 16) ^ ((u32)SBOX[(s3 >> 8) & 0xff] << 8) ^ (u32)SBOX[s0 & 0xff] ^ rk[1];
    t2 = ((u32)SBOX[s2 >> 24] << 24) ^ ((u32)SBOX[(s3 >> 16) & 0xff] << 16) ^ ((u32)SBOX[(s0 >> 8) & 0xff] << 8) ^ (u32)SBOX[s1 & 0xff] ^ rk[2];
    t3 = ((u32)SBOX[s3 >> 24] << 24) ^ ((u32)SBOX[(s0 >> 16) & 0xff] << 16) ^ ((u32)SBOX[(s1 >> 8) & 0xff] << 8) ^ (u32)SBOX[s2 & 0xff] ^ rk[3];
    STORE32_BE(out, t0); STORE32_BE(out + 4, t1); STORE32_BE(out + 8, t2); STORE32_BE(out + 12, t3);
}

void aes_decrypt_block(const aes_ctr_ctx *c, const u8 in[16], u8 out[16])
{
    const u32 *rk = c->drk;
    u32 s0, s1, s2, s3, t0, t1, t2, t3;
    int r;

    s0 = LOAD32_BE(in)      ^ rk[0];
    s1 = LOAD32_BE(in + 4)  ^ rk[1];
    s2 = LOAD32_BE(in + 8)  ^ rk[2];
    s3 = LOAD32_BE(in + 12) ^ rk[3];
    for (r = 1; r < c->rounds; r++) {
        rk += 4;
        t0 = TD0[s0 >> 24] ^ rk[0]; XOR_R8(t0, TD0[(s3 >> 16) & 0xff]); XOR_R16(t0, TD0[(s2 >> 8) & 0xff]); XOR_R24(t0, TD0[s1 & 0xff]);
        t1 = TD0[s1 >> 24] ^ rk[1]; XOR_R8(t1, TD0[(s0 >> 16) & 0xff]); XOR_R16(t1, TD0[(s3 >> 8) & 0xff]); XOR_R24(t1, TD0[s2 & 0xff]);
        t2 = TD0[s2 >> 24] ^ rk[2]; XOR_R8(t2, TD0[(s1 >> 16) & 0xff]); XOR_R16(t2, TD0[(s0 >> 8) & 0xff]); XOR_R24(t2, TD0[s3 & 0xff]);
        t3 = TD0[s3 >> 24] ^ rk[3]; XOR_R8(t3, TD0[(s2 >> 16) & 0xff]); XOR_R16(t3, TD0[(s1 >> 8) & 0xff]); XOR_R24(t3, TD0[s0 & 0xff]);
        s0 = t0; s1 = t1; s2 = t2; s3 = t3;
    }
    rk += 4;                                        /* last round: InvSubBytes + InvShiftRows only */
    t0 = ((u32)INV_SBOX[s0 >> 24] << 24) ^ ((u32)INV_SBOX[(s3 >> 16) & 0xff] << 16) ^ ((u32)INV_SBOX[(s2 >> 8) & 0xff] << 8) ^ (u32)INV_SBOX[s1 & 0xff] ^ rk[0];
    t1 = ((u32)INV_SBOX[s1 >> 24] << 24) ^ ((u32)INV_SBOX[(s0 >> 16) & 0xff] << 16) ^ ((u32)INV_SBOX[(s3 >> 8) & 0xff] << 8) ^ (u32)INV_SBOX[s2 & 0xff] ^ rk[1];
    t2 = ((u32)INV_SBOX[s2 >> 24] << 24) ^ ((u32)INV_SBOX[(s1 >> 16) & 0xff] << 16) ^ ((u32)INV_SBOX[(s0 >> 8) & 0xff] << 8) ^ (u32)INV_SBOX[s3 & 0xff] ^ rk[2];
    t3 = ((u32)INV_SBOX[s3 >> 24] << 24) ^ ((u32)INV_SBOX[(s2 >> 16) & 0xff] << 16) ^ ((u32)INV_SBOX[(s1 >> 8) & 0xff] << 8) ^ (u32)INV_SBOX[s0 & 0xff] ^ rk[3];
    STORE32_BE(out, t0); STORE32_BE(out + 4, t1); STORE32_BE(out + 8, t2); STORE32_BE(out + 12, t3);
}

/* out = in ^ ks over 16 bytes (out may equal in).  Four 32-bit XORs when all three pointers are
 * 4-byte aligned -- XOR is the same whatever the byte order -- otherwise the byte loop, so strict-
 * alignment CPUs (SPARC) never see a misaligned word access. */
static void xor16(u8 *out, const u8 *in, const u8 *ks)
{
    if ((((size_t)out | (size_t)in | (size_t)ks) & 3) == 0) {
        u32 *o = (u32 *)out;
        const u32 *a = (const u32 *)in, *b = (const u32 *)ks;
        o[0] = a[0] ^ b[0]; o[1] = a[1] ^ b[1]; o[2] = a[2] ^ b[2]; o[3] = a[3] ^ b[3];
    } else {
        int i;
        for (i = 0; i < 16; i++) out[i] = (u8)(in[i] ^ ks[i]);
    }
}

static void ctr_next(aes_ctr_ctx *c)               /* keystream for the current counter, then count */
{
    int j;
    aes_encrypt_block(c, c->ctr, c->ks);
    for (j = 15; j >= 0; j--) if (++c->ctr[j]) break;
}

void aes_ctr_xor(aes_ctr_ctx *c, const u8 *in, u8 *out, size_t len)
{
    while (len && c->used < 16) { *out++ = (u8)(*in++ ^ c->ks[c->used++]); len--; }    /* rest of the last block */
    while (len >= 16) {
        ctr_next(c);
        xor16(out, in, c->ks);
        in += 16; out += 16; len -= 16;
    }
    if (len) {
        ctr_next(c);
        c->used = 0;
        while (len) { *out++ = (u8)(*in++ ^ c->ks[c->used++]); len--; }
    }
}

/* ---------------- CBC (for encrypted private key files and the legacy SSH ciphers) ---------------- */

void aes_cbc_decrypt(const aes_ctr_ctx *c, const u8 iv[16], const u8 *in, u8 *out, size_t len)
{
    u8 prev[16], cur[16], plain[16];
    size_t off;
    memcpy(prev, iv, 16);
    for (off = 0; off + 16 <= len; off += 16) {
        memcpy(cur, in + off, 16);                         /* in and out may be the same buffer */
        aes_decrypt_block(c, cur, plain);
        xor16(out + off, plain, prev);
        memcpy(prev, cur, 16);
    }
}

void aes_cbc_encrypt_chain(const aes_ctr_ctx *c, u8 iv[16], const u8 *in, u8 *out, size_t len)
{
    u8 blk[16];
    size_t off;
    for (off = 0; off + 16 <= len; off += 16) {
        xor16(blk, in + off, iv);
        aes_encrypt_block(c, blk, out + off);
        memcpy(iv, out + off, 16);
    }
}

void aes_cbc_decrypt_chain(const aes_ctr_ctx *c, u8 iv[16], const u8 *in, u8 *out, size_t len)
{
    u8 cur[16], plain[16];
    size_t off;
    for (off = 0; off + 16 <= len; off += 16) {
        memcpy(cur, in + off, 16);
        aes_decrypt_block(c, cur, plain);
        xor16(out + off, plain, iv);
        memcpy(iv, cur, 16);
    }
}
