#!/usr/bin/env python3
"""Generate constant tables for the C core (run on the dev Mac, output is committed).

Everything is derived from first principles so we never hand-type constants:
  SHA-2 round constants  = frac(cbrt(prime)), IVs = frac(sqrt(prime))
  AES S-box              = GF(2^8) inverse + affine transform
  Curve25519 constants   = computed mod p = 2^255-19, packed as 16 x 16-bit limbs
"""
import sys

def primes(n):
    ps, c = [], 2
    while len(ps) < n:
        if all(c % p for p in ps):
            ps.append(c)
        c += 1
    return ps

def iroot(x, k):
    lo, hi = 0, 1 << ((x.bit_length() // k) + 2)
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if mid ** k <= x: lo = mid
        else: hi = mid - 1
    return lo

def frac_root(p, k, bits):
    return iroot(p << (bits * k), k) & ((1 << bits) - 1)

def emit_array(name, ctype, vals, width, per_line):
    out = ["static const %s %s[%d] = {" % (ctype, name, len(vals))]
    for i in range(0, len(vals), per_line):
        chunk = vals[i:i + per_line]
        if ctype == "u64":
            out.append("    " + ", ".join("0x%0*xULL" % (width, v) for v in chunk) + ",")
        elif ctype == "u32":
            out.append("    " + ", ".join("0x%0*xUL" % (width, v) for v in chunk) + ",")
        else:
            out.append("    " + ", ".join("0x%0*x" % (width, v) for v in chunk) + ",")
    out.append("};")
    return "\n".join(out)

def sha2():
    ps = primes(80)
    k256 = [frac_root(p, 3, 32) for p in ps[:64]]
    h256 = [frac_root(p, 2, 32) for p in ps[:8]]
    k512 = [frac_root(p, 3, 64) for p in ps]
    h512 = [frac_root(p, 2, 64) for p in ps[:8]]
    h384 = [frac_root(p, 2, 64) for p in ps[8:16]]
    s = "/* GENERATED by tools/gen_tables.py -- do not edit */\n"
    s += emit_array("K256", "u32", k256, 8, 4) + "\n\n"
    s += emit_array("H256_INIT", "u32", h256, 8, 4) + "\n\n"
    s += emit_array("K512", "u64", k512, 16, 2) + "\n\n"
    s += emit_array("H512_INIT", "u64", h512, 16, 2) + "\n\n"
    s += emit_array("H384_INIT", "u64", h384, 16, 2) + "\n"
    return s

def aes():
    def gmul(a, b):
        r = 0
        while b:
            if b & 1: r ^= a
            a <<= 1
            if a & 0x100: a ^= 0x11b
            b >>= 1
        return r
    def inv(a):
        if a == 0: return 0
        for b in range(1, 256):
            if gmul(a, b) == 1: return b
    sbox = []
    for i in range(256):
        b = inv(i)
        x = b
        for _ in range(4):
            b = ((b << 1) | (b >> 7)) & 0xff
            x ^= b
        sbox.append(x ^ 0x63)
    assert sbox[0] == 0x63 and sbox[1] == 0x7c and sbox[0x53] == 0xed
    s = "/* GENERATED by tools/gen_tables.py -- do not edit */\n"
    s += emit_array("SBOX", "u8", sbox, 2, 12) + "\n\n"
    inv = [0] * 256
    for i, v in enumerate(sbox): inv[v] = i
    s += emit_array("INV_SBOX", "u8", inv, 2, 12) + "\n"
    return s

P = (1 << 255) - 19

def limbs(v):
    v %= P
    return [(v >> (16 * i)) & 0xffff for i in range(16)]

def nacl():
    d = (-121665 * pow(121666, P - 2, P)) % P
    d2 = (2 * d) % P
    Gy = (4 * pow(5, P - 2, P)) % P
    # recover Gx: x^2 = (y^2-1)/(d*y^2+1), take the root with even parity (RFC 8032: x = 0x2169...)
    x2 = ((Gy * Gy - 1) * pow(d * Gy * Gy + 1, P - 2, P)) % P
    x = pow(x2, (P + 3) // 8, P)
    if (x * x - x2) % P: x = x * pow(2, (P - 1) // 4, P) % P
    assert (x * x - x2) % P == 0
    if x & 1: x = P - x
    Ic = pow(2, (P - 1) // 4, P)
    def arr(n, v):
        return "static const gf %s = {%s};" % (n, ", ".join("0x%04x" % l for l in limbs(v)))
    s = "/* GENERATED by tools/gen_tables.py -- do not edit */\n"
    s += arr("gf_D", d) + "\n" + arr("gf_D2", d2) + "\n" + arr("gf_X", x) + "\n"
    s += arr("gf_Y", Gy) + "\n" + arr("gf_I", Ic) + "\n"
    return s

def dh_groups():
    """RFC 3526 MODP groups 14 (2048-bit) and 16 (4096-bit): p = 2^n - 2^(n-64) - 1 + 2^64 * (floor(2^(n-130) * pi) + k).
    Verified here: published leading bytes, and p and (p-1)/2 both pass Miller-Rabin."""
    import random
    def pi_scaled(bits):                     # floor(pi * 2^bits), by Machin's formula
        scale = 1 << (bits + 64)
        def atan_inv(x):
            total = term = scale // x
            x2, n, sign = x * x, 1, -1
            while term:
                term //= x2; n += 2; total += sign * (term // n); sign = -sign
            return total
        return (4 * (4 * atan_inv(5) - atan_inv(239))) >> 64
    def is_prime(n, rounds=24):
        if n % 2 == 0: return False
        d, r = n - 1, 0
        while d % 2 == 0: d //= 2; r += 1
        rnd = random.Random(1234)
        for _ in range(rounds):
            a = rnd.randrange(2, n - 2)
            x = pow(a, d, n)
            if x in (1, n - 1): continue
            for _ in range(r - 1):
                x = x * x % n
                if x == n - 1: break
            else: return False
        return True
    out = ["/* GENERATED by tools/gen_tables.py (RFC 3526 MODP groups, generator g = 2) -- do not edit */"]
    for n, k, tag, head in ((2048, 124476, "P14", "FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD1"),
                            (4096, 240904, "P16", "FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD1")):
        p = (1 << n) - (1 << (n - 64)) - 1 + (1 << 64) * (pi_scaled(n - 130) + k)
        h = "%x" % p
        assert h.upper().startswith(head), "leading bytes differ from RFC 3526"
        assert p.bit_length() == n and is_prime(p) and is_prime((p - 1) // 2), "not a safe prime"
        out.append(emit_array("DH_%s" % tag, "u8", list(p.to_bytes(n // 8, "big")), 2, 16))
        print("  verified modp-%d: safe prime" % n)
    return "\n".join(out) + "\n"

def md5():
    import math
    k = [int(abs(math.sin(i + 1)) * (1 << 32)) & 0xffffffff for i in range(64)]
    assert k[0] == 0xd76aa478 and k[63] == 0xeb86d391, "MD5 constants"
    s = "/* GENERATED by tools/gen_tables.py -- do not edit */\n"
    s += emit_array("MD5_K", "u32", k, 8, 4) + "\n"
    return s

def curves():
    import subprocess, re
    out = ["/* GENERATED by tools/gen_tables.py from OpenSSL's curve definitions -- do not edit */"]
    def ec_add(P, Q, p, a):
        if P is None: return Q
        if Q is None: return P
        if P[0] == Q[0]:
            if (P[1] + Q[1]) % p == 0: return None
            lam = (3 * P[0] * P[0] + a) * pow(2 * P[1], p - 2, p) % p
        else:
            lam = (Q[1] - P[1]) * pow(Q[0] - P[0], p - 2, p) % p
        x = (lam * lam - P[0] - Q[0]) % p
        return (x, (lam * (P[0] - x) - P[1]) % p)
    def ec_mul(k, P, p, a):
        R = None
        while k:
            if k & 1: R = ec_add(R, P, p, a)
            P = ec_add(P, P, p, a)
            k >>= 1
        return R
    for name, tag, nbytes in (("prime256v1", "P256", 32), ("secp384r1", "P384", 48), ("secp521r1", "P521", 66)):
        txt = subprocess.run(["openssl", "ecparam", "-name", name, "-param_enc", "explicit", "-text", "-noout"],
                             capture_output=True, text=True, check=True).stdout
        blocks, key = {}, None
        for line in txt.splitlines():
            m = re.match(r"^(Prime|A|B|Generator \(uncompressed\)|Order):\s*(.*)$", line)
            if m: key = m.group(1).split()[0]; blocks[key] = m.group(2).strip(); continue
            if key and line.startswith(" ") and re.match(r"^\s+[0-9a-f:]+$", line): blocks[key] += line.strip()
            else: key = None
        num = lambda k: int(blocks[k].replace(":", "").replace("0x", ""), 16)
        p, a, b, n = num("Prime"), num("A"), num("B"), num("Order")
        gen = bytes.fromhex(blocks["Generator"].replace(":", ""))
        assert gen[0] == 4 and len(gen) == 1 + 2 * nbytes, name
        gx, gy = int.from_bytes(gen[1:1 + nbytes], "big"), int.from_bytes(gen[1 + nbytes:], "big")
        # independent verification of what OpenSSL told us
        assert a == p - 3, "a must be -3"
        assert (gy * gy - (gx ** 3 + a * gx + b)) % p == 0, "generator not on the curve"
        assert ec_mul(n, (gx, gy), p, a) is None, "n*G is not the point at infinity"
        assert ec_mul(n - 1, (gx, gy), p, a) == (gx, (-gy) % p), "(n-1)*G != -G"
        out.append("")
        for label, v in (("p", p), ("b", b), ("gx", gx), ("gy", gy), ("n", n)):
            out.append(emit_array("EC_%s_%s" % (tag, label), "u8", list(v.to_bytes(nbytes, "big")), 2, 16))
        print("  verified", name)
    return "\n".join(out) + "\n"

def blowfish():
    """Blowfish's P-array (18 words) and four S-boxes (4 x 256 words) are the first 1042
    32-bit words of the fractional part of pi.  Computed with Machin's formula in big integers."""
    nwords = 18 + 4 * 256
    bits = nwords * 32 + 96
    scale = 1 << (bits + 32)
    def arctan_inv(x):
        total = term = scale // x
        x2, n, sign = x * x, 1, -1
        while term:
            term //= x2
            n += 2
            total += sign * (term // n)
            sign = -sign
        return total
    pi = 4 * (4 * arctan_inv(5) - arctan_inv(239))
    frac = (pi - 3 * scale) >> 32
    words = [(frac >> (bits - 32 * (i + 1))) & 0xffffffff for i in range(nwords)]
    assert words[0] == 0x243F6A88 and words[1] == 0x85A308D3, "pi digits wrong"
    assert words[18] == 0xD1310BA6, "S0[0] wrong (Blowfish constant)"
    assert words[-1] == 0x3AC372E6, "last S-box word wrong (Blowfish constant)"
    s = "/* GENERATED by tools/gen_tables.py -- do not edit */\n"
    s += "/* Blowfish initial state: P[0..17] followed by S0[0..255], S1, S2, S3 (hex digits of pi) */\n"
    s += emit_array("BLF_PI", "u32", words, 8, 4) + "\n"
    return s

if __name__ == "__main__":
    base = sys.argv[1] if len(sys.argv) > 1 else "core"
    for name, fn in (("sha2_tab.h", sha2), ("aes_tab.h", aes), ("nacl_tab.h", nacl), ("blowfish_tab.h", blowfish), ("ecc_tab.h", curves), ("md5_tab.h", md5), ("dh_tab.h", dh_groups)):
        with open("%s/%s" % (base, name), "w") as f:
            f.write(fn())
        print("wrote", name)
