#!/usr/bin/env python3
"""tests/rsa_vectors.h -- RSA keys and PKCS#1 v1.5 signatures produced by OpenSSL."""
import subprocess, tempfile, os, re

MSG = b"OPENSTEP ssh client: RSA test message"
def run(*a): return subprocess.run(list(a), capture_output=True, check=True).stdout
def hexarr(name, b): return "static const unsigned char %s[%d] = {%s};" % (name, len(b), ",".join("0x%02x" % x for x in b))
def field(txt, name):
    m = re.search(name + r":\s*((?:[0-9a-f:\s])+?)(?=\n\S|\Z)", txt, re.S)
    return bytes.fromhex(re.sub(r"[^0-9a-f]", "", m.group(1)))

def main():
    d = tempfile.mkdtemp(); out = ["/* GENERATED by tools/gen_rsa_vectors.py -- do not edit */"]
    mp = os.path.join(d, "m"); open(mp, "wb").write(MSG)
    for idx, bits in enumerate((1024, 2048, 3072)):
        kp = os.path.join(d, "k%d.pem" % idx)
        run("openssl", "genrsa", "-out", kp, str(bits))
        txt = run("openssl", "rsa", "-in", kp, "-text", "-noout").decode()
        for nm, tag in (("modulus", "N"), ("privateExponent", "D"), ("prime1", "P"), ("prime2", "Q"), ("coefficient", "IQMP")):
            v = field(txt, nm); v = v.lstrip(b"\0")
            out.append(hexarr("RSA%d_%s" % (idx, tag), v))
        out.append(hexarr("RSA%d_E" % idx, (65537).to_bytes(3, "big")))
        for hname, tag in (("sha1", "SHA1"), ("sha256", "SHA256"), ("sha512", "SHA512")):
            sig = run("openssl", "dgst", "-" + hname, "-sign", kp, mp)
            out.append(hexarr("RSA%d_SIG_%s" % (idx, tag), sig))
    out.append("static const unsigned char RSA_MSG[] = \"%s\";" % MSG.decode())
    open("tests/rsa_vectors.h", "w").write("\n".join(out) + "\n")
    print("wrote tests/rsa_vectors.h")
main()
