#!/usr/bin/env python3
"""tests/bn_vectors.h: SHA-256 digests of big-integer results computed with Python's own integers.
Operands are regenerated in C from the same tiny generator, so only digests are embedded."""
import hashlib, sys

def operand(seed, nbytes, mode):
    if mode == 1: return bytes([0xff]) * nbytes
    if mode == 2: return bytes([0x80] + [0] * (nbytes - 2) + [1]) if nbytes > 1 else b"\x81"
    if mode == 3: return bytes([0x7f] + [0xff] * (nbytes - 1))
    if mode == 4: return bytes([0xff] * (nbytes - 1) + [0xfe])
    if mode == 5: return bytes([0x00, 0x00, 0x00, 0x01] + [0] * (nbytes - 4)) if nbytes > 4 else b"\x01"
    x, out = seed & 0xffffffff, bytearray()
    for _ in range(nbytes):
        x = (x * 1103515245 + 12345) & 0xffffffff
        out.append((x >> 20) & 0xff)
    if mode == 0: out[-1] |= 1                       # keep it nonzero
    return bytes(out)

def digest(n):
    b = n.to_bytes((n.bit_length() + 7) // 8, "big")
    return hashlib.sha256(b).digest()

# (seed_a, len_a, mode_a, seed_b, len_b, mode_b)
ARITH = [
    (1, 8, 0, 2, 4, 0), (3, 33, 0, 4, 17, 0), (5, 64, 0, 6, 32, 0), (7, 128, 0, 8, 64, 0),
    (9, 256, 0, 10, 128, 0), (11, 256, 0, 12, 255, 0), (13, 100, 0, 14, 1, 0), (15, 4, 0, 16, 4, 0),
    (17, 66, 0, 18, 65, 0), (19, 48, 0, 20, 48, 0),
    (0, 32, 1, 0, 16, 1), (0, 64, 1, 0, 33, 1), (0, 128, 1, 0, 64, 1),           # all ones
    (0, 33, 2, 0, 17, 2), (0, 64, 3, 0, 32, 2), (0, 65, 4, 0, 33, 3),            # add-back triggers
    (0, 36, 1, 0, 8, 2), (0, 40, 2, 0, 12, 3), (0, 72, 4, 0, 36, 4), (0, 12, 5, 0, 5, 0),
    (21, 7, 0, 22, 9, 0), (23, 1, 0, 24, 1, 0), (0, 16, 1, 0, 16, 1),
]
# (seed_b, len_b, seed_e, len_e, seed_m, len_m, force_odd)
MODEXP = [
    (31, 4, 32, 1, 33, 4, 1), (34, 32, 35, 3, 36, 32, 1), (37, 64, 38, 3, 39, 64, 1),       # e=RSA-ish
    (40, 128, 41, 128, 42, 128, 1), (43, 256, 44, 3, 45, 256, 1), (46, 128, 47, 64, 48, 128, 1),
    (49, 64, 50, 32, 51, 64, 0), (52, 30, 53, 30, 54, 31, 0), (55, 256, 56, 32, 57, 256, 1),
    (58, 66, 59, 66, 60, 66, 1), (61, 48, 62, 48, 63, 48, 1),
]

def main():
    o = ["/* GENERATED by tools/gen_bn_vectors.py -- do not edit */"]
    o.append("typedef struct { unsigned sa, la, ma, sb, lb, mb; } bn_arith_case;")
    o.append("static const bn_arith_case BN_ARITH[%d] = {" % len(ARITH))
    for c in ARITH: o.append("    {%s}," % ", ".join(str(v) for v in c))
    o.append("};")
    rows = []
    for sa, la, ma, sb, lb, mb in ARITH:
        a = int.from_bytes(operand(sa, la, ma), "big"); b = int.from_bytes(operand(sb, lb, mb), "big")
        if b == 0: b = 1
        hi, lo = max(a, b), min(a, b)
        rows.append([digest(a % b), digest(a // b), digest(a * b), digest(a + b), digest(hi - lo),
                     digest(a << 13), digest(a >> 45)])
    o.append("static const unsigned char BN_ARITH_EXP[%d][7][32] = {" % len(ARITH))
    for r in rows:
        o.append("  {" + ", ".join("{" + ",".join("0x%02x" % x for x in d) + "}" for d in r) + "},")
    o.append("};")
    o.append("typedef struct { unsigned sb, lb, se, le, sm, lm, odd; } bn_exp_case;")
    o.append("static const bn_exp_case BN_EXP[%d] = {" % len(MODEXP))
    for c in MODEXP: o.append("    {%s}," % ", ".join(str(v) for v in c))
    o.append("};")
    rows = []
    for sb, lb, se, le, so, lm, odd in MODEXP:
        b = int.from_bytes(operand(sb, lb, 0), "big"); e = int.from_bytes(operand(se, le, 0), "big")
        m = int.from_bytes(operand(so, lm, 0), "big")
        m |= 1 if odd else 0
        if not odd: m &= ~1                      # genuinely even
        if m < 3: m = 4 if not odd else 3
        rows.append(digest(pow(b, e, m)))
    o.append("static const unsigned char BN_EXP_EXP[%d][32] = {" % len(MODEXP))
    for d in rows: o.append("  {" + ",".join("0x%02x" % x for x in d) + "},")
    o.append("};")
    open("tests/bn_vectors.h", "w").write("\n".join(o) + "\n")
    print("wrote tests/bn_vectors.h")
main()
