#!/usr/bin/env python3
"""Generate term/nsenc_tab.h from tools/NEXTSTEP.TXT (forward table + sorted reverse table)."""
fwd = {}
for line in open("tools/NEXTSTEP.TXT"):
    if line.startswith("#") or not line.strip(): continue
    b, u = line.split()[:2]
    fwd[int(b, 16)] = int(u, 16)
assert sorted(fwd) == list(range(0x80, 0x100)), "table must cover 0x80..0xFF"
out = ["/* GENERATED by tools/gen_nsenc.py from tools/NEXTSTEP.TXT -- do not edit */",
       "static const unsigned short NS_TO_UNI[128] = {"]
for i in range(0x80, 0x100, 8):
    out.append("    " + ", ".join("0x%04x" % fwd[j] for j in range(i, i + 8)) + ",")
out.append("};\n")
rev = sorted((u, b) for b, u in fwd.items() if u != 0xfffd)
out.append("/* unicode -> NeXTSTEP byte, sorted by unicode for binary search */")
out.append("static const struct { unsigned short uni; unsigned char ns; } UNI_TO_NS[%d] = {" % len(rev))
for i in range(0, len(rev), 6):
    out.append("    " + ", ".join("{0x%04x, 0x%02x}" % r for r in rev[i:i + 6]) + ",")
out.append("};")
open("term/nsenc_tab.h", "w").write("\n".join(out) + "\n")
print("wrote term/nsenc_tab.h", len(rev), "reverse entries")
