#!/usr/bin/env python3
"""tests/ec_vectors.h -- NIST-curve test vectors from OpenSSL (signatures, ECDH) and Python (scalar mult)."""
import subprocess, tempfile, os, re, hashlib

CURVES = [("prime256v1", 32, "sha256"), ("secp384r1", 48, "sha384"), ("secp521r1", 66, "sha512")]
MSG = b"OPENSTEP ssh client: ECDSA test message"

def run(*a, inp=None):
    return subprocess.run(list(a), input=inp, capture_output=True, check=True).stdout

def hexarr(name, b):
    return "static const unsigned char %s[%d] = {%s};" % (name, len(b), ",".join("0x%02x" % x for x in b))

def parse_key(pem):
    txt = run("openssl", "ec", "-in", pem, "-text", "-noout").decode()
    priv = re.search(r"priv:\s*((?:[0-9a-f:\s])+?)pub:", txt, re.S).group(1)
    pub = re.search(r"pub:\s*((?:[0-9a-f:\s])+?)ASN1 OID", txt, re.S).group(1)
    clean = lambda s: bytes.fromhex(re.sub(r"[^0-9a-f]", "", s))
    return clean(priv), clean(pub)

def der_rs(sig):
    assert sig[0] == 0x30
    i = 2 if sig[1] < 0x80 else 2 + (sig[1] & 0x7f)
    out = []
    for _ in range(2):
        assert sig[i] == 2
        n = sig[i + 1]; out.append(int.from_bytes(sig[i + 2:i + 2 + n], "big")); i += 2 + n
    return out

def ec_ops(name):
    # Python reference arithmetic (affine), parameters read back from OpenSSL
    txt = run("openssl", "ecparam", "-name", name, "-param_enc", "explicit", "-text", "-noout").decode()
    blocks, key = {}, None
    for line in txt.splitlines():
        m = re.match(r"^(Prime|A|B|Generator \(uncompressed\)|Order):\s*(.*)$", line)
        if m: key = m.group(1).split()[0]; blocks[key] = m.group(2).strip(); continue
        if key and re.match(r"^\s+[0-9a-f:]+$", line): blocks[key] += line.strip()
        else: key = None
    num = lambda k: int(blocks[k].replace(":", ""), 16)
    p, a, n = num("Prime"), num("A"), num("Order")
    gen = bytes.fromhex(blocks["Generator"].replace(":", "")); nb = (len(gen) - 1) // 2
    G = (int.from_bytes(gen[1:1 + nb], "big"), int.from_bytes(gen[1 + nb:], "big"))
    def add(P, Q):
        if P is None: return Q
        if Q is None: return P
        if P[0] == Q[0]:
            if (P[1] + Q[1]) % p == 0: return None
            lam = (3 * P[0] * P[0] + a) * pow(2 * P[1], p - 2, p) % p
        else: lam = (Q[1] - P[1]) * pow(Q[0] - P[0], p - 2, p) % p
        x = (lam * lam - P[0] - Q[0]) % p
        return (x, (lam * (P[0] - x) - P[1]) % p)
    def mul(k, P):
        R = None
        while k:
            if k & 1: R = add(R, P)
            P = add(P, P); k >>= 1
        return R
    return G, mul, n, nb

def main():
    out = ["/* GENERATED by tools/gen_ec_vectors.py -- do not edit */"]
    d = tempfile.mkdtemp()
    for idx, (name, nb, hname) in enumerate(CURVES):
        G, mul, n, _ = ec_ops(name)
        # scalar multiplication
        k = int.from_bytes(hashlib.sha512(b"k%d" % idx).digest(), "big") % n
        P = mul(k, G)
        k2 = int.from_bytes(hashlib.sha512(b"kk%d" % idx).digest(), "big") % n
        R = mul(k2, P)
        out.append(hexarr("K%d" % idx, k.to_bytes(nb, "big")))
        out.append(hexarr("KG%d" % idx, b"\x04" + P[0].to_bytes(nb, "big") + P[1].to_bytes(nb, "big")))
        out.append(hexarr("K2%d" % idx, k2.to_bytes(nb, "big")))
        out.append(hexarr("K2KG%d" % idx, b"\x04" + R[0].to_bytes(nb, "big") + R[1].to_bytes(nb, "big")))
        # OpenSSL keys, signature, ECDH
        k1p, k2p = os.path.join(d, "a%d.pem" % idx), os.path.join(d, "b%d.pem" % idx)
        for kp in (k1p, k2p): open(kp, "wb").write(run("openssl", "ecparam", "-name", name, "-genkey", "-noout"))
        priv1, pub1 = parse_key(k1p); priv2, pub2 = parse_key(k2p)
        mp = os.path.join(d, "m.bin"); open(mp, "wb").write(MSG)
        sig = run("openssl", "dgst", "-" + hname, "-sign", k1p, mp)
        r, s = der_rs(sig)
        pub2pem = os.path.join(d, "b%dpub.pem" % idx); run("openssl", "ec", "-in", k2p, "-pubout", "-out", pub2pem)
        shared = run("openssl", "pkeyutl", "-derive", "-inkey", k1p, "-peerkey", pub2pem)
        assert len(shared) == nb
        out.append(hexarr("D%d" % idx, priv1.rjust(nb, b"\0")))
        out.append(hexarr("Q%d" % idx, pub1))
        out.append(hexarr("SR%d" % idx, r.to_bytes(nb, "big")))
        out.append(hexarr("SS%d" % idx, s.to_bytes(nb, "big")))
        out.append(hexarr("Q2_%d" % idx, pub2))
        out.append(hexarr("SHARED%d" % idx, shared))
        # the Python scalar-mult reference agrees with OpenSSL's public key for the same private key
        Pp = mul(int.from_bytes(priv1, "big"), G)
        assert b"\x04" + Pp[0].to_bytes(nb, "big") + Pp[1].to_bytes(nb, "big") == pub1
    out.append("static const unsigned char EC_MSG[] = \"%s\";" % MSG.decode())
    open("tests/ec_vectors.h", "w").write("\n".join(out) + "\n")
    print("wrote tests/ec_vectors.h")
main()
